# Site wide configuration

title:            data science ish
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Julia Silge
  avatar: bio-photo.jpg
  bio: "My name is Julia Silge and I’ve spent my career in academia and ed tech, working in physics and astronomy. Now I want to learn the tools used in data science and apply them to some small, interesting projects."
  email: julia.silge@gmail.com 
  disqus-shortname: 
  twitter: juliasilge
  facebook: julia.silge
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: juliasilge
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: juliasilge
  xing: #username
  instagram: juliasilge
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: silgeland

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
